spring:
  application:
    name: nabbreviate-api
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  sleuth:
    propagation:
      type: B3
  zipkin:
    baseUrl: http://158.220.124.12:30941/

server:
  servlet:
    context-path: /nabbreviate/v1
  port: ${PORT:8080}

management:
  tracing:
    sampling:
      probability: 1.0

tracing:
  url: http://158.220.124.12:32426/
#  url: http://localhost:4317

logging:
  level:
    root: info
    org.springframework.web: info
    io.opentelemetry.exporter.otlp.trace: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: info